name: Build CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            runner: ubuntu-latest
          - name: macOS
            runner: macos-latest
          - name: Windows
            runner: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6.0.2

      - name: Configure CMake
        run: >
          cmake
          -B ${{ github.workspace }}/build
          -S ${{ github.workspace }}
          -DBUILD_TESTING=ON

      - name: Build
        run: >
          cmake
          --build ${{ github.workspace }}/build

      - name: Run tests
        working-directory: ${{ github.workspace }}/build
        run: ctest --output-on-failure
