name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            runner: ubuntu-latest
            archive: tar.gz
          - name: macOS
            runner: macos-latest
            archive: tar.gz
          - name: Windows
            runner: windows-latest
            archive: zip
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6.0.2

      - name: Configure CMake
        run: >
          cmake
          -B ${{ github.workspace }}/build
          -S ${{ github.workspace }}
          -DBUILD_SHARED_LIBS=OFF
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install

      - name: Build
        run: >
          cmake
          --build ${{ github.workspace }}/build
          --config Release

      - name: Install
        run: >
          cmake
          --install ${{ github.workspace }}/build
          --config Release

      - name: Package artifacts (Linux/macOS)
        if: matrix.archive == 'tar.gz'
        run: >
          tar -czf
          ${{ github.workspace }}/utility-${{ matrix.name }}.tar.gz
          -C ${{ github.workspace }}/install .

      - name: Package artifacts (Windows)
        if: matrix.archive == 'zip'
        shell: pwsh
        run: >
          Compress-Archive
          -Path "${{ github.workspace }}\install\*"
          -DestinationPath "${{ github.workspace }}\utility-${{ matrix.name }}.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: ${{ github.workspace }}/utility-${{ matrix.name }}.${{ matrix.archive }}
          generate_release_notes: true
